version: "3.8"

services: 
  server:
    # here we are running this service by adding the images without docker file 
    # image: 'nginx:stable-alpine'
    # ports: 
    #   - '8000:80'
    build: 
      context: .    # here why the context is given like this, bcoz in ngix.dockerfile we refer to src and nginx folder which is outside docker files __dir
      dockerfile: dockerfiles/nginx.dockerfile # context not only specifies the folder where dockerfiles can be found , also specifies folder in which docker file build
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile.
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php","/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      -./src:/var/www/html